### ISSUE TITLE
Using wine-wayland both in x11 and wayland enviroment.

### ISSUE THREAD

**Issue by Firstbober** [varmd/wine-wayland#10]
Right now running wine-wayland on x11 shows `wayland display is not working` but it would be great if we could use some env var or auto detect to change backend making this patch work on both x11 and wayland.

**Comment by varmd** [comment]
wine-wayland requires a wayland compositor to run. X11 is not supported. You can use regular wine build on X11.

**Comment by toby63** [comment]
At first I couldn't understand this request, but it makes sense to be able to use normal wine alongside wine-wayland.
Some reasons and usecases include:
wine-wayland does not support every application and function.
Thanks to XWayland normal wine can be used in a wayland environment.
Some users switch between X11 and Wayland (this is possible in many ways, e.g. because Wayland can also be used as a X-Client).

So an "easy" solution would be to install wine-wayland seperate from normal wine (instead of replacing it) and then let the users decide which wine version is set as default for "wine".
