### ISSUE TITLE
Discussion: include your work in wine-tkg

### ISSUE THREAD

**Issue by AdelKS** [varmd/wine-wayland#13]
Hello!

I discovered your repository today and I find it nice to retrieve the various patches that are being worked on the make wine-wayland possible. 

I am opening this issue to ask about your thoughts on directly contributing to wine-tkg by providing the extra wine-wayland patches. It should reduce the amount of work you do, because you wouldn't have to mirror patches from wine-tkg here on top of the ones about enabling wayland. And that would make wine-tkg get more help !

I started a similar thread in wine-tkg [here](https://github.com/Frogging-Family/wine-tkg-git/issues/80) if you wanna have a look at it and maybe participate in the discussion.

**Comment by varmd** [comment]
wine-tkg is a separate project and relies extensively on X11, so it's not possible for wine-wayland to work there.

Regarding esync/fsync patches from wine-tkg here, since Wine 5.9 these patches no longer work. Currently, I rebased them to work with Wine 5.13 so for now "mirroring" from wine-tkg is not necessary and was never a big issue.

**Comment by AdelKS** [comment]
Understood! Maybe in the future then, it would be nice to make like a big wine repo that become the reference for gaming :D
