### ISSUE TITLE
Merge Collabora winewayland.drv

### ISSUE THREAD

**Issue by niobium93** [varmd/wine-wayland#26]
Not sure if this is something you're interested in doing, but figured I'd ask anyway - would it be feasible to merge the new GDI/OpenGL supporting Wine Wayland driver with this?
[RFC at wine-devel mailing list](https://www.winehq.org/pipermail/wine-devel/2020-December/178575.html)
[The code at gitlab](https://gitlab.collabora.com/alf/wine/-/commits/wayland)

**Comment by Faalagorn** [comment]
I've been curious as well, nothing is impossible I guess, but how feasible it is and how much work would it take merging it?

**Comment by varmd** [comment]
Since Collabora's winewayland is funded by Valve or RedHat, Codeweavers will eventually accept it to mainline Wine. So there is no point in spending effort of merging GDI/OpenGL support.

Additionally, there is already some GDI support in wine-wayland which is good enough for popups and simple launchers/apps. 

For the opengl support, most cards already support Vulkan, so there is no point in OpenGL support besides few launchers that seem to require it - but these have other issues.
