### ISSUE TITLE
Clarifications on usage

### ISSUE THREAD

**Issue by tigerjack** [varmd/wine-wayland#27]
I am trying experimenting with this project, but I'm still not sure what to put in the `.local/share/wineland` directory. 
More specifically, I am trying to run Pdf Xchange Editor (free version) with wineland. 

I tried several options.
1. I had a previous wine64 installation, located inside `{wine64dir}/drive_c/Program Files/Tracker Software/PDF Editor`. Furthermore, I tried to copy this directory inside `.local/share/wineland/pdfxchange` and set EXE path as `pdfxchange/PDFXEdit.exe`.
2. I tried to unzip the installer inside `.local/share/wineland/pdfxchange9`. I specified `pdfxchange9/PDFXVE9.exe` as EXE path.

In both cases, I used the default configurations. Starting from the command line, I get
```bash
>wineland pdfxchange9
kill: not enough arguments
pdfxchange9

/usr/lib/wineland/ui/start.sh: line 70: cd: /home/simone/.local/share/wineland/pdfxchange9/pdfxchange9: No such file or directory
is 32bit wine exe

rm: cannot remove '/home/simone/.local/share/wineland/pdfxchange9/wine/drive_c/users/simone/My Documents': Is a directory
/home/simone/.local/share/wineland/pdfxchange9/pdfxchange9
/home/simone/.local/share/wineland/pdfxchange9/wine/drive_c/pdfxchange9
/usr/lib/wineland/ui/start.sh: line 205: cd: /home/simone/.local/share/wineland/pdfxchange9/wine/drive_c/pdfxchange9: No such file or directory
```
So, my question is: what do I have to put inside the wineland dir to make it work?

**Comment by varmd** [comment]
This project focuses on running games with Wayland and Vulkan. GDI apps are currently not supported.

That said, I was able to run Pdf Xchange Editor on weston, by installing the msi version `wine64 msiexec /i EditorV9.x64.msi`, choosing Complete, then wine64 winefile and click on the lnk file in Desktop. It seemed to run pretty fast, and I was able to edit a large PDF but there were also crashes here and there. One of the reason why GDI apps are not supported, since most apps always have some issues or have no 64bit versions.

For your existing installation, you can do WINEPREFIX=wine64dir wine64 pathto64bitexe. You would need to run weston as wlroots compositors do not support subsurfaces properly - https://github.com/swaywm/wlroots/issues/1865. Gnome may also work. However, I'd suggest using a container if you want to remove X11 but still need some legacy windows GDI apps.

The wineland launcher requires copying the folder with the exe file - so it should have been ~/.local/share/wineland/pdfxchange9/PDFEditor and then EXE path set as PDFEditor/PDFXEdit.exe
